### PR TITLE
Update docker build to install Debian 11 dependencies

### PR DESCRIPTION
**Pull request by Kelly-ST-HRI**
# ramdaq pull request

理化学研究所のデベロッパー様、

お世話になっております。

H.U.グループ中央研究所のケリーと申します。ご対応を宜しくお願い致します。

Many thanks for developing ramdaq!

The current version causes a build error with the Dockerfile since Debian 10 (buster) is now "oldstable" and Debian 11 (bullseye) is "stable". This PR adds an additional step to install Debian dependencies from the new version. It runs `docker built -t ramdaq:latest .` without errors.

This is a minor bug I think further testing is not necessary. Please tell me if you have any questions.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Ensure the test suite passes (`nextflow run rikenbit/ramdaq -profile test,docker`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

### CODE REVIEW

**Comment by myoshimura080822** [comment]
@Kelly-ST-HRI Thank you for your pull request to help us deal with the issue related to the Dockerfile. Unfortunately, the test for the docker build process is not included in our CI testing. So we are currently working on the docker build tests in the development environment. We will get back to you soon.

**Comment by Kelly-ST-HRI** [comment]
@myoshimura080822  Thanks for considering it Yoshimura-san! Sorry for the duplicate PRs, I was unsure which branch was meant to be used to pass GitHub Actions checks and merge.

I suppose the current checks do not matter in this case as docker builds are not tested yet and no other files were changed. If it helps, I will share an example of automated checks on Docker builds from my previous lab.

https://github.com/minoda-lab/universc/blob/master/.github/workflows/docker-test-build.yml

We disabled automation on this at RIKEN IMS as we had problems with GitHub LFS bandwidth to install it and some jobs timed out. It was working nicely before. I hope it is helpful for you to implement testing on the Dockerfile to ensure it works on the latest version of the nfcore docker base image.

**Comment by myoshimura080822** [comment]
@Kelly-ST-HRI 
We will merge this pull request since the build was completed successfully in our development environment. We also appreciate your suggestion in resolving the issue and Dockerfile CI testing.

**Comment by Kelly-ST-HRI** [comment]
@myoshimura080822 Thank you for taking time to test it. Happy to help.

ありがとうございました。ご対応を宜しくお願い致します。

**Pull request merged**
